from crewai import Agent
from langchain_ollama import OllamaLLM

llm = OllamaLLM(model="llama3.2:3b", base_url="http://ollama:11434")

def ai_detector_agent():
    return Agent(
        role="AI Detection Specialist",
        goal="Detect whether a candidate's answer was generated by an AI/LLM",
        backstory=(
            "You are a specialist in identifying AI-generated text. You analyze linguistic patterns "
            "such as overly formal structure, lack of personal anecdotes, perfect grammar with no "
            "hesitation markers, generic examples, and suspiciously comprehensive coverage of all "
            "sub-topics. You assign an AI likelihood score from 0-100 with reasoning."
        ),
        llm=llm,
        verbose=True,
        allow_delegation=False,
    )
