import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                '..', '..', '..', 'interview-service'))
from config import OLLAMA_BASE_URL, OLLAMA_MODEL
from crewai import Agent, LLM

llm = LLM(model=f"ollama/{OLLAMA_MODEL}", base_url=OLLAMA_BASE_URL)

def ai_detector_agent():
    return Agent(
        role="AI Detection Specialist",
        goal="Detect whether a candidate's answer was generated by an AI/LLM",
        backstory=(
            "You are a specialist in identifying AI-generated text. You analyze linguistic patterns "
            "such as overly formal structure, lack of personal anecdotes, perfect grammar with no "
            "hesitation markers, generic examples, and suspiciously comprehensive coverage of all "
            "sub-topics. You assign an AI likelihood score from 0-100 with reasoning."
        ),
        llm=llm,
        verbose=True,
        allow_delegation=False,
    )
